### ISSUE TITLE
[Issue]: An event handler (f) didn't receive enough output values (needed: 4, received: 3).

### ISSUE THREAD

**Issue by oldboss918** [vladmandic/automatic#862]
### Issue Description

Traceback (most recent call last):
  File "D:\WORK\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\WORK\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\WORK\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1206, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "D:\WORK\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1181, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 4, received: 3).

Wanted outputs:
    [textbox, label, label, html]
Received outputs:
    [None, "", "<div class='error'>ImportError: cannot import name &#x27;onnxruntime_validation&#x27; from &#x27;onnxruntime.capi&#x27; (D:\WORK\sd-webui-aki-v4\py310\lib\site-packages\onnxruntime\capi\__init__.py)</div><div class='performance'><p class='time'>Time taken: <wbr>0.78s</p><p class='vram'>Torch active/reserved: 1/32 MiB, <wbr>Sys VRAM: 820/4096 MiB (20.02%)</p></div>"]

### Version Platform Description

AUTO1111 brach id： 5ab7f213bec2f816f9c5644becb32eb72c8ffb89 (2023-05-02 14:20:35)
I tried to switch versions, but it didn't work.

**Comment by vladmandic** [comment]
first, what is the workflow leading to this? traceback is nice to have, but i cannot be guessing what were you doing that lead to it.

btw, you're not using venv? how are you starting the app?

and what are the versions of: `pip show onnx onnxruntime`?

**Comment by vladmandic** [comment]
any updates?

**Comment by vladmandic** [comment]
closing as no information provided, will reopen if information becomes available.

**Comment by richielg** [comment]
I have the same error and the issue is when i'm trying to do a batch run of 10 settings.txt files in deforum, they work individually but not as a batch. First time i've tried batches and not working. Automatic 1111 on osx ventura 13.6.4, deforum version 3.0, A1111 version: [v1.6.0]  ( python: 3.10.9  •  torch: 2.0.1  • gradio: 3.41.2.

Two error messages firstly:  TypeError: 'types.SimpleNamespace' object is not subscriptable

secondly:  raise ValueError(
ValueError: An event handler (run_deforum) didn't receive enough output values (needed: 4, received: 3).
Wanted outputs:
    [gallery, textbox, textbox, html]
Received outputs:
    [None, "", "<div class='error'>TypeError: &#x27;types.SimpleNamespace&#x27; object is not subscriptable</div><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>19 min. 37.9 sec.</span></p></div>"]

**Comment by vladmandic** [comment]
this is NOT A1111, open issue in correct repo.
also, commenting on an issue closed a year ago never does much.
