### ISSUE TITLE
[Issue]: Control + ControlNet raises exception on starting generation (regression from c42fded960e188be5aab35d6754eac876e599e44)

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3112]
### Issue Description

When setting up a ControlNet run (e.g. with images from #3083) and hitting Generate, the pipeline immediately fails with

```
2024-05-08 22:09:09.077	ERROR	sd	ui_control	Control exception: 'StableDiffusionXLInpaintPipeline' object has no attribute '__name__'
2024-05-08 22:09:09.081	ERROR	sd	errors	Control: AttributeError
```

I've seen this in two different installs, with different stacks (one ROCm and the other CUDA).

The issue lies in c42fded960e188be5aab35d6754eac876e599e44. In particular, in `modules/control/units/detect.py`, which moved from

```
 return isinstance(model, p.StableDiffusionXLPipeline) or isinstance(model, p.StableDiffusionXLImg2ImgPipeline) or isinstance(model, p.StableDiffusionXLInpaintPipeline)
```

to 

```
return model.__name__ == p.StableDiffusionXLPipeline.__name__ or model.__name__ == p.StableDiffusionXLImg2ImgPipeline.__name__ or model.__name__ == p.StableDiffusionXLInpaintPipeline.__name__
```

but `StableDiffusionXLInpaintPipeline` doesn't have `__name__` and thus everything breaks.

### Version Platform Description

Dev as of 0b420eaf4458f8367378f5ea675252597cb64dae.

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by lbeltrame** [comment]
Actually it regressed earlier. Not sure when. Anyway, this is a traceback (obtained after rolling back to b137f67edcd35364cd70623b99bafbfcd6c031fc:

```
20:21:02-794752 ERROR    Control exception: 'StableDiffusionXLPipeline' object  
                         has no attribute '__name__'                            
20:21:02-796756 ERROR    Control: AttributeError                                
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /notebooks/automatic/modules/ui_control.py:56 in generate_click              │
│                                                                              │
│    55 │   │   try:                                                           │
│ ❱  56 │   │   │   for results in control_run(units, helpers.input_source, he │
│    57 │   │   │   │   progress.record_results(job_id, results)               │
│                                                                              │
│ /notebooks/automatic/modules/control/run.py:259 in control_run               │
│                                                                              │
│   258 │   │   p.task_args['guess_mode'] = p.guess_mode                       │
│ ❱ 259 │   │   instance = controlnet.ControlNetPipeline(selected_models, shar │
│   260 │   │   pipe = instance.pipeline                                       │
│                                                                              │
│ /notebooks/automatic/modules/control/units/controlnet.py:193 in __init__     │
│                                                                              │
│   192 │   │   │   return                                                     │
│ ❱ 193 │   │   elif detect.is_sdxl(pipeline):                                 │
│   194 │   │   │   self.pipeline = StableDiffusionXLControlNetPipeline(       │
│                                                                              │
│ /notebooks/automatic/modules/control/units/detect.py:12 in is_sdxl           │
│                                                                              │
│   11 │   │   return False                                                    │
│ ❱ 12 │   return model.__name__ == p.StableDiffusionXLPipeline.__name__ or mo │
│   13 │   # return isinstance(model, p.StableDiffusionXLPipeline) or isinstan │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py:142 │
│                                                                              │
│   141 │   │                                                                  │
│ ❱ 142 │   │   raise AttributeError(f"'{type(self).__name__}' object has no a │
│   143                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'StableDiffusionXLPipeline' object has no attribute '__name__'
```

**Comment by lbeltrame** [comment]
And this is a traceback with the same inputs on latest dev. Notice the wrong pipeline (Inpaint) as well.

```
22:31:16-277485 ERROR    Control exception: 'StableDiffusionXLInpaintPipeline' object has no attribute '__name__'                                                                                                                                           
22:31:16-279983 ERROR    Control: AttributeError                                                                                                                                                                                                            
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ /home/lb/Coding/automatic/modules/ui_control.py:56 in generate_click                                                                                                                                                                                     │
│                                                                                                                                                                                                                                                          │
│    55 │   │   try:                                                                                                                                                                                                                                       │
│ ❱  56 │   │   │   for results in control_run(units, helpers.input_source, helpers.input_init, helpers.input_mask, active_tab, True, *args):                                                                                                              │
│    57 │   │   │   │   progress.record_results(job_id, results)                                                                                                                                                                                           │
│                                                                                                                                                                                                                                                          │
│ /home/lb/Coding/automatic/modules/control/run.py:259 in control_run                                                                                                                                                                                      │
│                                                                                                                                                                                                                                                          │
│   258 │   │   p.task_args['guess_mode'] = p.guess_mode                                                                                                                                                                                                   │
│ ❱ 259 │   │   instance = controlnet.ControlNetPipeline(selected_models, shared.sd_model)                                                                                                                                                                 │
│   260 │   │   pipe = instance.pipeline                                                                                                                                                                                                                   │
│                                                                                                                                                                                                                                                          │
│ /home/lb/Coding/automatic/modules/control/units/controlnet.py:193 in __init__                                                                                                                                                                            │
│                                                                                                                                                                                                                                                          │
│   192 │   │   │   return                                                                                                                                                                                                                                 │
│ ❱ 193 │   │   elif detect.is_sdxl(pipeline):                                                                                                                                                                                                             │
│   194 │   │   │   self.pipeline = StableDiffusionXLControlNetPipeline(                                                                                                                                                                                   │
│                                                                                                                                                                                                                                                          │
│ /home/lb/Coding/automatic/modules/control/units/detect.py:12 in is_sdxl                                                                                                                                                                                  │
│                                                                                                                                                                                                                                                          │
│   11 │   │   return False                                                                                                                                                                                                                                │
│ ❱ 12 │   return model.__name__ == p.StableDiffusionXLPipeline.__name__ or model.__name__ == p.StableDiffusionXLImg2ImgPipeline.__name__ or model.__name__ == p.StableDiffusionXLInpaintPipeline.__name__                                                 │
│   13 │   # return isinstance(model, p.StableDiffusionXLPipeline) or isinstance(model, p.StableDiffusionXLImg2ImgPipeline) or isinstance(model, p.StableDiffusionXLInpaintPipeline)                                                                       │
│                                                                                                                                                                                                                                                          │
│ /home/lb/Coding/automatic/venv/lib64/python3.11/site-packages/diffusers/configuration_utils.py:142 in __getattr__                                                                                                                                        │
│                                                                                                                                                                                                                                                          │
│   141 │   │                                                                                                                                                                                                                                              │
│ ❱ 142 │   │   raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")                                                                                                                                                          │
│   143                                                                                                                                                                                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'StableDiffusionXLInpaintPipeline' object has no attribute '__name__'
```
