### ISSUE TITLE
[Issue]: NoneType' object has no attribute 'decode' - Diffusers mode + refiner

### ISSUE THREAD

**Issue by Kedaranatha** [vladmandic/automatic#2141]
### Issue Description

Getting an error after updating to 26e18b0a. Deleting and performing a fresh install didn't fix the problem

in Diffusers mode + refiner, error for refiner step "NoneType' object has no attribute 'decode'" , see log

### Version Platform Description

win 11
app: SD.next
updated: 2023-09-06
hash: 26e18b0a
device: NVIDIA GeForce RTX 3090 (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700
driver: 537.13
active: cuda
dtype: torch.float16
vae: torch.float16
unet: torch.float16

### Relevant log output

```shell
Progress  1.94it/s ████████████████▊                  51% 30/59 00:15 00:14 Base
15:10:27-022286 ERROR    Exception: 'NoneType' object has no attribute 'decode'
15:10:27-023288 ERROR    Arguments: args=('task(47etinif0dk9we5)', 'plant medicine', '', [], 30, 5, 0, True, False,
                         False, 1, 1, 7.5, 6, 0.7, 1, -1.0, -1.0, 0, 0, 0, 1152, 896, True, 0.3, 2, 'None', 20, 0, 0, 5,
                         0.8, '', '', [], 0, False, False, 'positive', 'comma', 0, False, False, '', 0, '', [], 0, '',
                         [], 0, '', [], True, False, False, False, 0, False) kwargs={}
15:10:27-026286 ERROR    gradio call: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\SD.next\modules\call_queue.py:34 in f                                                                             │
│                                                                                                                      │
│   33 │   │   │   try:                                                                                                │
│ ❱ 34 │   │   │   │   res = func(*args, **kwargs)                                                                     │
│   35 │   │   │   │   progress.record_results(id_task, res)                                                           │
│                                                                                                                      │
│ C:\SD.next\modules\txt2img.py:65 in txt2img                                                                          │
│                                                                                                                      │
│   64 │   if processed is None:                                                                                       │
│ ❱ 65 │   │   processed = processing.process_images(p)                                                                │
│   66 │   p.close()                                                                                                   │
│                                                                                                                      │
│ C:\SD.next\modules\processing.py:608 in process_images                                                               │
│                                                                                                                      │
│    607 │   │   else:                                                                                                 │
│ ❱  608 │   │   │   res = process_images_inner(p)                                                                     │
│    609 │   finally:                                                                                                  │
│                                                                                                                      │
│ C:\SD.next\modules\processing.py:767 in process_images_inner                                                         │
│                                                                                                                      │
│    766 │   │   │   │   from modules.processing_diffusers import process_diffusers                                    │
│ ❱  767 │   │   │   │   x_samples_ddim = process_diffusers(p, p.seeds, p.prompts, p.negative_pro                      │
│    768                                                                                                               │
│                                                                                                                      │
│ C:\SD.next\modules\processing_diffusers.py:371 in process_diffusers                                                  │
│                                                                                                                      │
│   370 │   │   for i in range(len(output.images)):                                                                    │
│ ❱ 371 │   │   │   refiner_args = set_pipeline_args(                                                                  │
│   372 │   │   │   │   model=shared.sd_refiner,                                                                       │
│                                                                                                                      │
│                                               ... 8 frames hidden ...                                                │
│                                                                                                                      │
│ C:\SD.next\venv\lib\site-packages\compel\compel.py:282 in _get_conditioning_for_flattened_prompt                     │
│                                                                                                                      │
│   281 │   │   weights = [x.weight for x in prompt.children]                                                          │
│ ❱ 282 │   │   return self.conditioning_provider.get_embeddings_for_weighted_prompt_fragments(                        │
│   283 │   │   │   text_batch=[fragments], fragment_weights_batch=[weights],                                          │
│                                                                                                                      │
│ C:\SD.next\venv\lib\site-packages\compel\embeddings_provider.py:119 in get_embeddings_for_weighted_prompt_fragments  │
│                                                                                                                      │
│   118 │   │   │   # handle weights >=1                                                                               │
│ ❱ 119 │   │   │   tokens, per_token_weights, mask = self.get_token_ids_and_expand_weights(frag                       │
│   120 │   │   │   base_embedding = self.build_weighted_embedding_tensor(tokens, per_token_weig                       │
│                                                                                                                      │
│ C:\SD.next\venv\lib\site-packages\compel\embeddings_provider.py:270 in get_token_ids_and_expand_weights              │
│                                                                                                                      │
│   269 │   │   │   weights = [1.0]                                                                                    │
│ ❱ 270 │   │   per_fragment_token_ids = self.get_token_ids(fragments, include_start_and_end_mar                       │
│   271 │   │   all_token_ids: List[int] = []                                                                          │
│                                                                                                                      │
│ C:\SD.next\venv\lib\site-packages\compel\embeddings_provider.py:226 in get_token_ids                                 │
│                                                                                                                      │
│   225 │   │   │   if self.textual_inversion_manager is not None:                                                     │
│ ❱ 226 │   │   │   │   token_ids = self.textual_inversion_manager.expand_textual_inversion_toke                       │
│   227                                                                                                                │
│                                                                                                                      │
│ C:\SD.next\modules\prompt_parser_diffusers.py:71 in expand_textual_inversion_token_ids_if_necessary                  │
│                                                                                                                      │
│    70 │   │   │   return token_ids                                                                                   │
│ ❱  71 │   │   prompt = self.pipe.tokenizer.decode(token_ids)                                                         │
│    72 │   │   prompt = self.maybe_convert_prompt(prompt, self.pipe.tokenizer)                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'decode'
```

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by afbagwell** [comment]
I just got this too after successfully running a prompt and then only adding the refiner before running it again.

**Comment by vladmandic** [comment]
make sure you're on latest build as first version from today had a known issue.
and if issues persist, then we'll take it from there.

**Comment by Kedaranatha** [comment]
Yep. Issue still there I’ve updated a log https://discord.com/channels/1101998836328697867/1149104588801183784Sent from my iPhoneOn Sep 6, 2023, at 8:25 PM, Vladimir Mandic ***@***.***> wrote:﻿
make sure you're on latest build as first version from today had a known issue.
and if issues persist, then we'll take it from there.

**Comment by xedis** [comment]
Can confirm Issue remains. 
[sdnext-with profiling console output.log](https://github.com/vladmandic/automatic/files/12545422/sdnext-with.profiling.console.output.log)
Fresh venv.

**Comment by Kedaranatha** [comment]
It looks like this problem relates to the 'Full parser.' or so. I just changed it for an experiment to 'Fixed attention,' and I see it has disappeared.

00:46:52-510914 INFO     Loading diffusers VAE: models\VAE\sdxl_vae.safetensors source=settings
00:47:22-702375 INFO     Loading diffusers VAE: models\VAE\sdxl_vae.safetensors source=settings
Progress  1.32it/s █████████████████████████████████ 100% 24/24 00:18 00:00 Base
Progress  1.22it/s ██████████████████████████████ 100% 37/37 00:30 00:00 Refiner
00:48:29-958744 INFO     Processed: images=1 time=66.00s its=0.45 memory={'ram': {'used': 1.73, 'total': 63.93}, 'gpu':
                         {'used': 16.43, 'total': 24.0}, 'retries': 0, 'oom': 0}
00:48:31-119744 INFO     Loading diffusers VAE: models\VAE\sdxl_vae.safetensors source=settings

**Comment by vladmandic** [comment]
fixed. issue was with newly added textual inversion support for sdxl which should be skipped for refiner pass.
